all: skip looking for package comments in .git/ repository
The `.git/` directory is the Git repository and not part of the
working tree.

This patch fixes spurious failures because something inside `.git/`
has a `.go` suffix. For example, there’s a branch named
`c22wen/magicsock.go` which is definitely not a Go source file.

    sfllaw@host:~/tailscale$ git fetch origin c22wen/magicsock.go
    From https://github.com/tailscale/tailscale
     * branch                c22wen/magicsock.go -> FETCH_HEAD
    sfllaw@host:~/tailscale$ go test . -run 'TestPackageDocs'
    === RUN   TestPackageDocs
        pkgdoc_test.go:46: failed to ParseFile ".git/logs/refs/remotes/origin/c22wen/magicsock.go": .git/logs/refs/remotes/upstream/c22wen/magicsock.go:1:1: expected 'package', found 0000000000000000000000000000000000000000 (and 1 more errors)
    --- FAIL: TestPackageDocs (0.01s)
    FAIL
    FAIL	tailscale.com	0.015s
    FAIL

Fixes: #15383

Signed-off-by: Simon Law <sfllaw@sfllaw.ca>